apiVersion: v1
kind: Service
metadata:
  name: {{ include "xlsform-builder.frontendFullname" . }}
  labels:
    {{- include "xlsform-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    {{- include "xlsform-builder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: http
