apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xlsform-builder.frontendFullname" . }}
  labels:
    {{- include "xlsform-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      {{- include "xlsform-builder.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "xlsform-builder.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          env:
            - name: VITE_API_URL
              value: {{ .Values.frontend.env.apiUrl | quote }}
            - name: VITE_METADATA_URL
              value: {{ .Values.frontend.env.metadataUrl | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.frontend.port }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
