{{- if .Values.llama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xlsform-builder.llamaFullname" . }}
  labels:
    {{- include "xlsform-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: llama
spec:
  type: {{ .Values.service.llama.type }}
  selector:
    {{- include "xlsform-builder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: llama
  ports:
    - name: http
      port: {{ .Values.service.llama.port }}
      targetPort: http
{{- end }}
