apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xlsform-builder.pyxformFullname" . }}
  labels:
    {{- include "xlsform-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: pyxform
spec:
  replicas: {{ .Values.replicaCount.pyxform }}
  selector:
    matchLabels:
      {{- include "xlsform-builder.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pyxform
  template:
    metadata:
      labels:
        {{- include "xlsform-builder.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pyxform
    spec:
      containers:
        - name: pyxform
          image: "{{ .Values.image.pyxform.repository }}:{{ .Values.image.pyxform.tag }}"
          imagePullPolicy: {{ .Values.image.pyxform.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.pyxform.port }}
          {{- if .Values.pyxform.healthCheck.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.pyxform.healthCheck.path }}
              port: http
          livenessProbe:
            httpGet:
              path: {{ .Values.pyxform.healthCheck.path }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources.pyxform | nindent 12 }}
