apiVersion: v1
kind: Service
metadata:
  name: {{ include "xlsform-builder.pyxformFullname" . }}
  labels:
    {{- include "xlsform-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: pyxform
spec:
  type: {{ .Values.service.pyxform.type }}
  selector:
    {{- include "xlsform-builder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pyxform
  ports:
    - name: http
      port: {{ .Values.service.pyxform.port }}
      targetPort: http
